# Generated by Django 3.2.9 on 2021-11-01 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='description',
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='New', max_length=50),
        ),
    ]
