# Generated by Django 3.2.9 on 2021-11-01 14:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='due_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
